"""add surname to AuthorModel.

Revision ID: a78340ef557a
Revises: 6defdc48515a
Create Date: 2021-03-03 11:23:53.647079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78340ef557a'
down_revision = '6defdc48515a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_model', sa.Column('surname', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'author_model', ['surname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author_model', type_='unique')
    op.drop_column('author_model', 'surname')
    # ### end Alembic commands ###
